apiVersion: apps/v1
kind: Deployment
metadata:
  name: intel-hero
  namespace: default
spec:
  selector:
    matchLabels:
      app: intel-hero
  replicas: 3
  template:
    metadata:
      labels:
        app: intel-hero
    spec:
      containers:
        - name: intel-hero-container
          image: akarx/intel-hero:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: intel-hero-service
  namespace: default
spec:
  selector:
    app: intel-hero
  type: NodePort
  ports:
    - name: app
      port: 80
      targetPort: 3000
      nodePort: 30300
